require 'base64'
require 'json'
require 'logger'
require 'shellwords'

repo_root = File.expand_path('../../..', __dir__)
a9s_bin = File.join(repo_root, 'bin', 'a9s')
if File.exist?(a9s_bin)
  ENV['PATH'] = "#{File.dirname(a9s_bin)}:#{ENV['PATH']}"
end

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  # https://rspec.info/features/3-12/rspec-core/configuration/zero-monkey-patching-mode/
  config.disable_monkey_patching!

  # This setting enables warnings. It's recommended, but in some cases may
  # be too noisy due to issues in dependencies.
  config.warnings = true

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end

def log_file
  file = File.new('test.log', 'w+')

  # Write log messages immediately to the file.
  file.sync = true
  file
end

def aws_cli_available?
  system("command -v aws >/dev/null 2>&1")
end

def aws_credentials_available?
  system("aws sts get-caller-identity >/dev/null 2>&1")
end

def aws_region_available?
  ENV["AWS_REGION"].to_s != "" || ENV["AWS_DEFAULT_REGION"].to_s != ""
end

def klutch_control_plane_region
  ENV.fetch("A9S_E2E_KLUTCH_REGION", "eu-central-1").to_s.strip
end

def aws_find_vpc_id_by_tags(tags, region:)
  filters = tags.map { |k, v| "Name=tag:#{k},Values=#{v}" }
  args = ["aws", "ec2", "describe-vpcs", "--filters", *filters, "--query", "Vpcs[0].VpcId", "--output", "text"]
  args += ["--region", region] unless region.to_s.strip.empty?
  cmd = Shellwords.join(args)
  logger.info(cmd)

  vpc_id = `#{cmd}`.strip
  return "" if vpc_id.empty? || vpc_id == "None" || vpc_id == "null"

  vpc_id
end

def aws_vpc_exists?(vpc_id, region:)
  args = ["aws", "ec2", "describe-vpcs", "--vpc-ids", vpc_id]
  args += ["--region", region] unless region.to_s.strip.empty?
  cmd = Shellwords.join(args) + " >/dev/null 2>&1"
  logger.info(cmd)
  system(cmd)
end

def aws_verify_vpc_deleted(vpc_id, region:, timeout_seconds: 600, sleep_seconds: 10)
  deadline = Time.now + timeout_seconds
  loop do
    return unless aws_vpc_exists?(vpc_id, region: region)
    if Time.now >= deadline
      raise "VPC #{vpc_id} still exists in region #{region} after #{timeout_seconds}s"
    end
    sleep(sleep_seconds)
  end
end

def aws_verify_vpc_exists(tags, region:, timeout_seconds: 600, sleep_seconds: 10)
  deadline = Time.now + timeout_seconds
  loop do
    vpc_id = aws_find_vpc_id_by_tags(tags, region: region)
    return vpc_id unless vpc_id.empty?
    if Time.now >= deadline
      raise "No VPC found with tags #{tags.inspect} in region #{region} after #{timeout_seconds}s"
    end
    sleep(sleep_seconds)
  end
end

def aws_cognito_user_pool_ids(region:)
  args = ["aws", "cognito-idp", "list-user-pools", "--max-results", "50", "--query", "UserPools[].Id", "--output", "text"]
  args += ["--region", region] unless region.to_s.strip.empty?
  cmd = Shellwords.join(args)
  logger.info(cmd)

  out = `#{cmd}`.strip
  return [] unless $?.success?
  strings = out.split
  strings.reject(&:empty?)
end

def aws_cognito_user_pool_tags(pool_id, region:)
  arn_args = ["aws", "cognito-idp", "describe-user-pool", "--user-pool-id", pool_id, "--query", "UserPool.Arn", "--output", "text"]
  arn_args += ["--region", region] unless region.to_s.strip.empty?
  arn_cmd = Shellwords.join(arn_args)
  logger.info(arn_cmd)

  arn = `#{arn_cmd}`.strip
  return {} unless $?.success? && !arn.empty? && arn != "None" && arn != "null"

  args = ["aws", "cognito-idp", "list-tags-for-resource", "--resource-arn", arn, "--query", "Tags", "--output", "json"]
  args += ["--region", region] unless region.to_s.strip.empty?
  cmd = Shellwords.join(args)
  logger.info(cmd)

  out = `#{cmd}`.strip
  return {} unless $?.success? && !out.empty? && out != "null" && out != "None"

  JSON.parse(out)
rescue JSON::ParserError
  {}
end

def aws_find_cognito_user_pool_id_by_tags(tags, region:)
  aws_cognito_user_pool_ids(region: region).each do |pid|
    pool_tags = aws_cognito_user_pool_tags(pid, region: region)
    next if pool_tags.empty?
    return pid if tags.all? { |k, v| pool_tags[k] == v }
  end
  ""
end

def aws_verify_cognito_user_pool_exists(tags, region:, timeout_seconds: 600, sleep_seconds: 10)
  deadline = Time.now + timeout_seconds
  loop do
    pool_id = aws_find_cognito_user_pool_id_by_tags(tags, region: region)
    return pool_id unless pool_id.empty?
    if Time.now >= deadline
      raise "No Cognito user pool found with tags #{tags.inspect} in region #{region} after #{timeout_seconds}s"
    end
    sleep(sleep_seconds)
  end
end

def aws_secretsmanager_secret_exists?(secret_name, region:)
  args = ["aws", "secretsmanager", "describe-secret", "--secret-id", secret_name, "--query", "ARN", "--output", "text"]
  args += ["--region", region] unless region.to_s.strip.empty?
  cmd = Shellwords.join(args) + " >/dev/null 2>&1"
  logger.info(cmd)
  system(cmd)
end

def aws_verify_secretsmanager_secret_exists(secret_name, region:, timeout_seconds: 600, sleep_seconds: 10)
  deadline = Time.now + timeout_seconds
  loop do
    return if aws_secretsmanager_secret_exists?(secret_name, region: region)
    if Time.now >= deadline
      raise "Secrets Manager secret #{secret_name} not found in region #{region} after #{timeout_seconds}s"
    end
    sleep(sleep_seconds)
  end
end

def dns_ns_resolvable?(zone)
  zone = zone.to_s.strip
  return false if zone.empty?

  if system("command -v dig >/dev/null 2>&1")
    output = `dig +short NS #{Shellwords.escape(zone)} @8.8.8.8 2>/dev/null`.strip
    return !output.empty?
  end

  if system("command -v nslookup >/dev/null 2>&1")
    output = `nslookup -type=NS #{Shellwords.escape(zone)} 8.8.8.8 2>/dev/null`
    return output.include?("nameserver")
  end

  false
end

def logger
  $logger ||= Logger.new log_file
  $logger.level = Logger::INFO
  $logger
end

def kubectl_create_namespace(namespace)
  cmd = "kubectl create namespace " + namespace
  logger.info(cmd)

  ret = system(cmd)
  raise "Can't create namespace" unless ret
end

def reuse_cluster?
  ENV["A9S_E2E_REUSE_CLUSTER"] == "1"
end

def kubectl_ensure_namespace(namespace)
  cmd = "kubectl get namespace #{namespace} >/dev/null 2>&1 || kubectl create namespace #{namespace}"
  logger.info(cmd)
  ret = system(cmd)
  raise "Can't ensure namespace #{namespace}" unless ret
end

def a9s_backup_store_config_file
  File.expand_path("~/a9s/a8s-deployment/deploy/a8s/backup-config/backup-store-config.yaml")
end

def delete_a9s_backup_store_config
  FileUtils.rm(a9s_backup_store_config_file) if File.exist?(a9s_backup_store_config_file)
end

def kubectl_service_binding_exists?(name, namespace)
  cmd = "kubectl get servicebinding #{name} -n #{namespace} --ignore-not-found -o name 2>/dev/null"
  logger.info(cmd)
  output = `#{cmd}`.strip
  !output.empty?
end

def kubectl_service_binding_implemented?(name, namespace)
  cmd = "kubectl get servicebinding #{name} -n #{namespace} -o jsonpath='{.status.implemented}' 2>/dev/null"
  logger.info(cmd)
  output = `#{cmd}`.strip
  output == "true"
end

def kubectl_verify_service_binding_exists(name, namespace)
  unless kubectl_service_binding_exists?(name, namespace)
    raise "Service binding #{name} does not exist in namespace #{namespace}"
  end
end

def kubectl_verify_service_binding_implemented(name, namespace)
  unless kubectl_service_binding_implemented?(name, namespace)
    raise "Service binding #{name} is not implemented in namespace #{namespace}"
  end
end

def kubectl_verify_service_binding_not_exists(name, namespace)
  if kubectl_service_binding_exists?(name, namespace)
    raise "Service binding #{name} still exists in namespace #{namespace}"
  end
end

def kubectl_secret_exists?(name, namespace)
  cmd = "kubectl get secret #{name} -n #{namespace} --ignore-not-found -o name 2>/dev/null"
  logger.info(cmd)
  output = `#{cmd}`.strip
  !output.empty?
end

def kubectl_verify_secret_exists(name, namespace)
  unless kubectl_secret_exists?(name, namespace)
    raise "Secret #{name} does not exist in namespace #{namespace}"
  end
end

def kubectl_verify_secret_not_exists(name, namespace, timeout_seconds: 60, sleep_seconds: 5)
  deadline = Time.now + timeout_seconds
  loop do
    return unless kubectl_secret_exists?(name, namespace)
    if Time.now >= deadline
      raise "Secret #{name} still exists in namespace #{namespace} after #{timeout_seconds}s"
    end
    sleep(sleep_seconds)
  end
end

def kubectl_secret_data(name, namespace, key)
  cmd = "kubectl get secret #{name} -n #{namespace} -o jsonpath='{.data.#{key}}' 2>/dev/null"
  logger.info(cmd)
  encoded = `#{cmd}`.strip
  if encoded.empty?
    raise "Secret #{name} in namespace #{namespace} does not contain key #{key}"
  end
  Base64.decode64(encoded).strip
end

def kubectl_service_exists?(name, namespace)
  cmd = "kubectl get service #{name} -n #{namespace} --ignore-not-found -o name 2>/dev/null"
  logger.info(cmd)
  output = `#{cmd}`.strip
  !output.empty?
end

def kubectl_verify_service_exists(name, namespace)
  unless kubectl_service_exists?(name, namespace)
    raise "Service #{name} does not exist in namespace #{namespace}"
  end
end

def kubectl_verify_service_not_exists(name, namespace, timeout_seconds: 60, sleep_seconds: 5)
  deadline = Time.now + timeout_seconds
  loop do
    return unless kubectl_service_exists?(name, namespace)
    if Time.now >= deadline
      raise "Service #{name} still exists in namespace #{namespace} after #{timeout_seconds}s"
    end
    sleep(sleep_seconds)
  end
end

def kubectl_pg_service_instance_exists?(name, namespace)
  cmd = "kubectl get postgresqls #{name} -n #{namespace} --ignore-not-found -o name 2>/dev/null"
  logger.info(cmd)
  output = `#{cmd}`.strip
  !output.empty?
end

def kubectl_verify_pg_service_instance_exists(name, namespace)
  unless kubectl_pg_service_instance_exists?(name, namespace)
    raise "Service instance #{name} does not exist in namespace #{namespace}"
  end
end

def kubectl_verify_pg_service_instance_not_exists(name, namespace)
  if kubectl_pg_service_instance_exists?(name, namespace)
    raise "Service instance #{name} still exists in namespace #{namespace}"
  end
end

def kubectl_pg_backup_exists?(name, namespace)
  cmd = "kubectl get backups #{name} -n #{namespace} --ignore-not-found -o name 2>/dev/null"
  logger.info(cmd)
  output = `#{cmd}`.strip
  !output.empty?
end

def kubectl_verify_pg_backup_exists(name, namespace)
  unless kubectl_pg_backup_exists?(name, namespace)
    raise "Backup #{name} does not exist in namespace #{namespace}"
  end
end

def kubectl_pg_condition_status(resource, name, namespace, condition_type)
  cmd = "kubectl get #{resource} #{name} -n #{namespace} -o jsonpath='{.status.conditions[?(@.type==\"#{condition_type}\")].status}' 2>/dev/null"
  logger.info(cmd)
  `#{cmd}`.strip
end

def kubectl_verify_pg_condition_true(resource, name, namespace, condition_type)
  status = kubectl_pg_condition_status(resource, name, namespace, condition_type)
  unless status.casecmp("True").zero?
    raise "#{resource} #{name} in namespace #{namespace} does not have condition #{condition_type}=True (status=#{status})"
  end
end

def kubectl_pg_restore_exists?(name, namespace)
  cmd = "kubectl get restores #{name} -n #{namespace} --ignore-not-found -o name 2>/dev/null"
  logger.info(cmd)
  output = `#{cmd}`.strip
  !output.empty?
end

def kubectl_verify_pg_restore_exists(name, namespace)
  unless kubectl_pg_restore_exists?(name, namespace)
    raise "Restore #{name} does not exist in namespace #{namespace}"
  end
end

def kubectl_crd_exists?(name)
  cmd = "kubectl get crd #{name} --ignore-not-found -o name 2>/dev/null"
  logger.info(cmd)
  output = `#{cmd}`.strip
  !output.empty?
end

def kubectl_verify_crd_exists(name)
  unless kubectl_crd_exists?(name)
    raise "CRD #{name} does not exist in the cluster"
  end
end

def kubectl_verify_pg_pods_running(name, namespace, replicas)
  replicas.times do |i|
    pod_name = "#{name}-#{i}"
    cmd = "kubectl get pod #{pod_name} -n #{namespace} -o jsonpath='{.status.phase}' 2>/dev/null"
    logger.info(cmd)
    status = `#{cmd}`.strip
    unless status == "Running"
      raise "Pod #{pod_name} is not running (status=#{status})"
    end
  end
end

def kubectl_pg_master_pod_name(name, namespace)
  label_selector = "a8s.a9s/replication-role=master,a8s.a9s/dsi-group=postgresql.anynines.com,a8s.a9s/dsi-name=#{name}"
  cmd = "kubectl get pods -n #{namespace} -l #{label_selector} -o jsonpath='{.items[0].metadata.name}' 2>/dev/null"
  logger.info(cmd)
  pod = `#{cmd}`.strip
  if pod.empty?
    raise "No master pod found for service instance #{name} in namespace #{namespace}"
  end
  pod
end

def kubectl_psql_select_one(pod_name, namespace, host, username, password, database)
  host_arg = Shellwords.escape(host)
  user_arg = Shellwords.escape(username)
  db_arg = Shellwords.escape(database)
  password_env = Shellwords.escape(password)
  cmd = "kubectl exec -n #{namespace} #{pod_name} -- env PGPASSWORD=#{password_env} psql -h #{host_arg} -U #{user_arg} -d #{db_arg} -tAc 'SELECT 1'"
  logger.info(cmd)
  output = `#{cmd}`.strip
  unless $?.success?
    raise "psql command failed: #{cmd}\n#{output}"
  end
  output
end

def kubectl_verify_pg_pods_not_exists(name, namespace, replicas, timeout_seconds: 120, sleep_seconds: 5)
  deadline = Time.now + timeout_seconds

  loop do
    missing = true
    replicas.times do |i|
      pod_name = "#{name}-#{i}"
      cmd = "kubectl get pod #{pod_name} -n #{namespace} --ignore-not-found -o name 2>/dev/null"
      logger.info(cmd)
      output = `#{cmd}`.strip
      unless output.empty?
        missing = false
        break
      end
    end

    return if missing

    if Time.now >= deadline
      raise "Pods for #{name} still exist in namespace #{namespace} after #{timeout_seconds}s"
    end
    sleep(sleep_seconds)
  end
end

def kubectl_verify_pods_running_by_label(namespace, label_selector)
  cmd = "kubectl get pods -n #{namespace} -l #{label_selector} -o jsonpath='{.items[*].status.phase}' 2>/dev/null"
  logger.info(cmd)
  phases = `#{cmd}`.strip
  unless phases.split.any? { |p| p == "Running" }
    raise "No running pods found in #{namespace} with label #{label_selector} (phases=#{phases})"
  end
end

def kubectl_tenant_ready?(name, namespace:)
  args = ["kubectl", "get", "tenants.klutch.anynines.com", name, "-n", namespace, "-o", "json"]
  cmd = Shellwords.join(args)
  logger.info(cmd)
  out = `#{cmd}`.strip
  return false unless $?.success? && !out.empty?

  data = JSON.parse(out)
  status = data["status"] || {}
  phase = status["phase"].to_s.strip
  return true if phase.casecmp("Ready").zero?

  conditions = status["conditions"]
  if conditions.is_a?(Array)
    conditions.each do |cond|
      next unless cond.is_a?(Hash)
      next unless cond["status"].to_s.strip.casecmp("True").zero?
      type = cond["type"].to_s.strip
      return true if ["Ready", "CredentialsReady", "IdPReady"].any? { |t| t.casecmp(type).zero? }
    end
  end

  oidc = status["oidc"]
  if oidc.is_a?(Hash)
    client_id = oidc["clientID"].to_s.strip
    issuer = oidc["issuer"].to_s.strip
    return true unless client_id.empty? || issuer.empty?
  end

  false
rescue JSON::ParserError
  false
end

def kubectl_wait_for_tenant_ready(name, namespace:, timeout_seconds: 600, sleep_seconds: 10)
  deadline = Time.now + timeout_seconds
  loop do
    return if kubectl_tenant_ready?(name, namespace: namespace)
    if Time.now >= deadline
      raise "Tenant #{namespace}/#{name} did not become ready after #{timeout_seconds}s"
    end
    sleep(sleep_seconds)
  end
end
