apiVersion: anynines.com/v1
kind: Backup
metadata:
  name: example-a8s-postgresql
  namespace: default
spec: 
  instanceRef: example-a8s-postgresql
  serviceInstanceType: postgresql
  compositionRef:
    name: a8s-backup
